[package]
name = "fib-wasm"
version = "0.1.0"
authors = ["Chojan Shang <psiace@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
crate-type = ["cdylib"]

[profile.release]
incremental = false
panic = "abort"
lto = true
opt-level = "z"
